all : ProcesadorYodafy.java YodafyClienteTCP.java YodafyServidorIterativo.java Hebra.java
	javac ProcesadorYodafy.java YodafyClienteTCP.java YodafyServidorIterativo.java Hebra.java

clean :
	rm -r *.class