all : ProcesadorYodafy.java YodafyClienteUDP.java YodafyServidorIterativo.java Hebra.java
	javac ProcesadorYodafy.java YodafyClienteUDP.java YodafyServidorIterativo.java Hebra.java

clean :
	rm -r *.class